name: Build third-party-licenses.txt
run-name: Build third-party-licenses.txt
on: [push]
jobs:
  Build-Third-Party-Licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Generate third-party-licenses.txt
        run: |
          cd frontend
          npx license-checker-rseidelsohn --production --out public/third-party-licenses.txt --customPath ./licenseFormat.json --excludePackages yaba_client
      - name: Finish up
        run: echo 'Done.'
